// Generated by CoffeeScript 1.6.3
var __slice = [].slice;

module.exports = function(moment) {
  var tzid, zone, zones, _fn;
  moment.formats = {
    day: 'YYYY-MM-DD',
    numberedDay: 'YYYYMMDD',
    abbrv: 'ddd, MMM Do',
    long: 'dddd, MMMM Do',
    short: 'MMM D',
    weekday: 'dddd'
  };
  moment.day = function(day, tzid) {
    return moment.tz(day, [moment.formats.day, moment.formats.numberedDay], tzid);
  };
  moment.fn.dayString = function() {
    return this.format(moment.formats.day);
  };
  zones = {
    eastern: 'America/New_York',
    central: 'America/Chicago',
    mountain: 'America/Denver',
    pacific: 'America/Los_Angeles'
  };
  _fn = function(zone, tzid) {
    moment[zone] = function() {
      var args;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      args.push(tzid);
      return moment.tz.apply(this, args);
    };
    return moment[zone].tzid = tzid;
  };
  for (zone in zones) {
    tzid = zones[zone];
    _fn(zone, tzid);
  }
  return moment;
};
