// Generated by CoffeeScript 1.6.3
var __slice = [].slice;

module.exports = function(moment) {
  var tzid, zone, zones, _fn;
  moment.day = function(day, tzid) {
    return moment.tz(day, [moment.day.DASHED_DAY, moment.day.NUMBER_DAY], tzid);
  };
  moment.day.DASHED_DAY = 'YYYY-MM-DD';
  moment.day.NUMBER_DAY = 'YYYYMMDD';
  moment.fn.toDay = function() {
    return this.format(moment.day.DASHED_DAY);
  };
  zones = {
    eastern: 'America/New_York',
    central: 'America/Chicago',
    pacific: 'America/Los_Angeles'
  };
  _fn = function(zone, tzid) {
    moment[zone] = function() {
      var args;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      args.push(tzid);
      return moment.tz.apply(this, args);
    };
    return moment[zone].tzid = tzid;
  };
  for (zone in zones) {
    tzid = zones[zone];
    _fn(zone, tzid);
  }
  return moment;
};
