// Generated by CoffeeScript 1.7.1
var moment;

moment = typeof window !== "undefined" && window !== null ? window.moment : void 0;

if (moment == null) {
  throw new Error('geomoment expects moment to be loaded');
}

moment.tz.add(require('../data/usa.json'));

window.geomoment = require('./')(moment);
