// Generated by CoffeeScript 1.7.1
if ((typeof window !== "undefined" && window !== null ? window.geomoment : void 0) == null) {
  throw new Error('geomoment expects moment to be loaded');
}

moment.tz.add(require('../data/usa.json'));

window.geomoment = require('./')(moment);
