// Generated by CoffeeScript 1.6.3
var augment, moment, usa;

moment = require('moment-timezone/moment-timezone');

augment = require('./augment_moment');

usa = require('../data/usa');

moment.tz.add(usa);

module.exports = augment(moment);
