// Generated by CoffeeScript 1.6.3
var augment, latest, moment;

moment = require('moment-timezone');

augment = require('./augment_moment');

latest = require('../data/latest.json');

moment.tz.load(latest);

module.exports = augment(moment);
