// Generated by CoffeeScript 1.6.3
var stubbedTime;

stubbedTime = null;

module.exports = function(year, month, day, hour, minute, second, millisecond) {
  if (year == null) {
    if (stubbedTime != null) {
      return new Date(stubbedTime.valueOf());
    }
    return new Date();
  }
  if (month == null) {
    return new Date(year);
  }
  return new Date(year, month, day, hour, minute, second, millisecond);
};

module.exports.stubTime = function(date) {
  return stubbedTime = date;
};

module.exports.restoreTime = function() {
  return stubbedTime = null;
};
